#!/usr/bin/env bash
# Installs Nginx and creates a file.
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple index.html file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

# Start nginx service
sudo service nginx start
