#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop
counter=1

while [ $counter -le 10 ]
do
  if [ $counter == 9 ]; then
	  echo "Hi"
  else
	  echo "Best School"
  fi
  counter=$((counter + 1))
done
