#!/usr/bin/env bash
# Configures a ufw firewall:

#Installs ufw
sudo apt-get update
sudo apt-get install -y ufw

# Allow Outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable Fire Wall
sudo ufw enable
