#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

#Installs ufw
sudo apt-get update
sudo apt-get install -y ufw

# Allow Outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# Enable Fire Wall
sudo ufw enable
