#!/usr/bin/env bash
#Run Nginx as nginx
sudo pkill apache2
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
